% Plot Diagnostic Tests and Treatment Wait Times for NHS England Between April 2008 and September 2020

function [] = PlotExtractedData() 
    [WaitingTimes, TotalMortality, ~, CovidUnrelatedMortality] = ReadAndProcessAllData();

    dateAxis = datetime(WaitingTimes.Year, WaitingTimes.Month, 1);

    figure(1)
    hold on

    totalWaitingListBar = bar(dateAxis, WaitingTimes.Total_Waiting);
    waiting6PlusWeeksBar = bar(dateAxis, WaitingTimes.Waiting_6_Plus_Weeks);
    waiting13PlusWeeksBar = bar(dateAxis, WaitingTimes.Waiting_13_Plus_Weeks);

    totalWaitingListBar.FaceColor = '#0072BD';
    waiting6PlusWeeksBar.FaceColor = '#EDB120';
    waiting13PlusWeeksBar.FaceColor = '#D95319';

    title('Diagnostic Tests and Treatment Wait Times for NHS England Between April 2008 and September 2020',...
        'HorizontalAlignment', 'center',...
        'FontWeight', 'bold',...
        'FontSize', 18);
    legend('Total on Waiting List', 'Waiting 6+ Weeks', 'Waiting 13+ Weeks',...
        'FontSize', 14)
    xlabel('Date',...
        'FontWeight', 'bold',...
        'FontSize', 14)
    ylabel('No. Patients',...
        'FontWeight', 'bold',...
        'FontSize', 14)
    hold off

    % Plot Mortality in England Between April 2008 and September 2020
    figure(2)
    hold on
    totalMortalitybar = bar(dateAxis, TotalMortality.Mortality);

    covidUnrelatedMortalityBar = bar(...
        datetime(CovidUnrelatedMortality.Year, CovidUnrelatedMortality.Month, 1),...
        CovidUnrelatedMortality.Mortality);

    totalMortalitybar.FaceColor = '#D95319';
    covidUnrelatedMortalityBar.FaceColor = '#0072BD';

    title('Mortality in England Between April 2008 and September 2020',...
        'HorizontalAlignment', 'center',...
        'FontWeight', 'bold',...
        'FontSize', 18);
    legend('Deaths Due to COVID-19', 'Deaths Unrelated to COVID-19',...
        'FontSize', 14)
    xlabel('Date',...
        'FontWeight', 'bold',...
        'FontSize', 14)
    ylabel('No. Deaths',...
        'FontWeight', 'bold',...
        'FontSize', 14)
    hold off
end